name: Linux

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      build_config:
        description: 'Comma-separated "Release" and/or "Debug"'
        default: '"Release", "Debug"'
        required: true
      clang_version: 
        description: 'Comma-separated "17" and/or "18" and/or "19"'
        default: '"17", "18", "19"'
        required: true
      gcc_version: 
        description: 'Comma-separated "11" and/or "12" and/or "13"'
        default: '"11", "12", "13"'
        required: true

jobs:
  ubuntu_clang:
    name: Ubuntu | Clang
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_config: ${{ fromJSON(format('[{0}]', inputs.build_config || '"Release", "Debug"')) }}
        clang_version: ${{ fromJSON(format('[{0}]', inputs.clang_version || '"17", "18", "19"')) }}

    env:
      clang_compiler_version: -${{ matrix.clang_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install suitable compiler
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh ${{ matrix.clang_version }}

      - name: Install CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Build CppProfiler
        uses: lukka/run-cmake@v10
        with:
          # This is the name of the CMakePresets.json's configuration to use to generate
          # the project files.
          configurePreset: "Clang"
          
          # This is the name of the CMakePresets.json's configuration to build the project.
          buildPreset: "Clang ${{ matrix.build_config }}"
      
      - name: Runtime test DirectBuild+ProfilerEnabled
        uses: threeal/ctest-action@v1.0.0
        with:
          test-dir: out/build/Clang/src/Tests/DirectBuild/ProfilerEnabled
          build-config: ${{ matrix.build_config }}
        
      - name: Runtime test DirectBuild+ProfilerDisabled
        uses: threeal/ctest-action@v1.0.0
        with:
          test-dir: out/build/Clang/src/Tests/DirectBuild/ProfilerDisabled
          build-config: ${{ matrix.build_config }}
      
      - name: Runtime test SharedLibraryLink+ProfilerEnabled
        uses: threeal/ctest-action@v1.0.0
        with:
          test-dir: out/build/Clang/src/Tests/SharedLibraryLink/ProfilerEnabled
          build-config: ${{ matrix.build_config }}
      
      - name: Runtime test SharedLibraryLink+ProfilerDisabled
        uses: threeal/ctest-action@v1.0.0
        with:
          test-dir: out/build/Clang/src/Tests/SharedLibraryLink/ProfilerDisabled
          build-config: ${{ matrix.build_config }}


  ubuntu_gcc:
    name: Ubuntu | GCC
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_config: ${{ fromJSON(format('[{0}]', inputs.build_config || '"Release", "Debug"')) }}
        gcc_version: ${{ fromJSON(format('[{0}]', inputs.gcc_version || '"11", "12", "13"')) }}

    env:
      gcc_compiler_version: -${{ matrix.gcc_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install suitable compiler
        run: sudo apt-get install gcc-${{ matrix.gcc_version }} g++-${{ matrix.gcc_version }}

      - name: Install CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Build CppProfiler
        uses: lukka/run-cmake@v10
        with:
          # This is the name of the CMakePresets.json's configuration to use to generate
          # the project files.
          configurePreset: "GCC"
          
          # This is the name of the CMakePresets.json's configuration to build the project.
          buildPreset: "GCC ${{ matrix.build_config }}"
      
      - name: Runtime test DirectBuild+ProfilerEnabled
        uses: threeal/ctest-action@v1.0.0
        with:
          test-dir: out/build/GCC/src/Tests/DirectBuild/ProfilerEnabled
          build-config: ${{ matrix.build_config }}
        
      - name: Runtime test DirectBuild+ProfilerDisabled
        uses: threeal/ctest-action@v1.0.0
        with:
          test-dir: out/build/GCC/src/Tests/DirectBuild/ProfilerDisabled
          build-config: ${{ matrix.build_config }}
      
      - name: Runtime test SharedLibraryLink+ProfilerEnabled
        uses: threeal/ctest-action@v1.0.0
        with:
          test-dir: out/build/GCC/src/Tests/SharedLibraryLink/ProfilerEnabled
          build-config: ${{ matrix.build_config }}
      
      - name: Runtime test SharedLibraryLink+ProfilerDisabled
        uses: threeal/ctest-action@v1.0.0
        with:
          test-dir: out/build/GCC/src/Tests/SharedLibraryLink/ProfilerDisabled
          build-config: ${{ matrix.build_config }}